name: Docker Image node js app


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
      

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: build_push_tag of main
     
      
      env:      
       PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       USERNAME: ${{ secrets.DOCKER_USERNAME }}  
      
     
      run: |
            
             sudo docker login -u $USERNAME -p $PASSWORD
             sudo docker build -t aadi308/mm:${{ github.sha }} -f Dockerfile .  
             sudo docker push aadi308/mm:${{ github.sha }}
         
             
  deploy:
 
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: deploy app
      
      
      run: sudo docker-compose  up -d
